spring.application.name=auth-service

server.port=4005


SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgres:5432/authdb
SPRING_DATASOURCE_PASSWORD=auth
SPRING_DATASOURCE_USERNAME=auth 
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_SQL_INIT_MODE=always

