server:
  port: 4003

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: lb://patient-service:4000
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - strip-perfix=2