### save new patient
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
  "name": "Tatiens Sikbawi ",
  "email": "isabella.walker@example.com",
  "address": "Alma Bagi, zaprafkanin arxasinda",
  "dateOfBirth": "2000-12-24",
  "dateOfRegistration": "2026-09-09"
}