### save new patient
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
  "id": "asdkjfaioweofi12345678woej",
  "name": "Sikiminbawiens Sikbawi ",
  "email": "internalnetworktest2@gmail.com",
  "address": "Alma Bagi, pakoilden biraz yuxari",
  "dateOfBirth": "2000-12-24",
  "dateOfRegistration": "2026-09-09"
}