spring.application.name=patient-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/patientdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:patient}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:patient}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

server.port=${SERVER_PORT:4000}
