plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.protobuf' version '0.9.5'
}

group = 'com.rradjabli'
version = '0.0.1-SNAPSHOT'
description = 'billing-service'



java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    grpcVersion = '1.63.0'
    protobufVersion = '3.25.1'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation "net.devh:grpc-server-spring-boot-starter:3.1.0.RELEASE"
    implementation "net.devh:grpc-client-spring-boot-starter:3.1.0.RELEASE"

    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"
    implementation "com.google.protobuf:protobuf-java:${protobufVersion}"

    compileOnly "org.apache.tomcat:annotations-api:6.0.53"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }

    generateProtoTasks {
        all().configureEach {
            plugins {
                grpc {}
            }
        }
    }
}